back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"